"""Version 0.6_Last Updated 20171121"""

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, TournamentController):
        TournamentController.setObjectName("TournamentController")
        TournamentController.resize(1145, 791)
        TournamentController.setAutoFillBackground(False)
        self.centralwidget = QtWidgets.QWidget(TournamentController)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox.sizePolicy().hasHeightForWidth())
        self.groupBox.setSizePolicy(sizePolicy)
        self.groupBox.setMinimumSize(QtCore.QSize(200, 0))
        self.groupBox.setMaximumSize(QtCore.QSize(600, 16777215))
        self.groupBox.setObjectName("groupBox")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.findMatchB = QtWidgets.QPushButton(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.findMatchB.sizePolicy().hasHeightForWidth())
        self.findMatchB.setSizePolicy(sizePolicy)
        self.findMatchB.setMinimumSize(QtCore.QSize(0, 50))
        self.findMatchB.setObjectName("findMatchB")
        self.gridLayout_5.addWidget(self.findMatchB, 1, 0, 1, 1)
        self.saveB = QtWidgets.QPushButton(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.saveB.sizePolicy().hasHeightForWidth())
        self.saveB.setSizePolicy(sizePolicy)
        self.saveB.setMinimumSize(QtCore.QSize(0, 50))
        self.saveB.setObjectName("saveB")
        self.gridLayout_5.addWidget(self.saveB, 0, 0, 1, 1)
        self.editB = QtWidgets.QPushButton(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.editB.sizePolicy().hasHeightForWidth())
        self.editB.setSizePolicy(sizePolicy)
        self.editB.setMinimumSize(QtCore.QSize(0, 50))
        self.editB.setObjectName("editB")
        self.gridLayout_5.addWidget(self.editB, 2, 0, 1, 1)
        self.exitB = QtWidgets.QPushButton(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.exitB.sizePolicy().hasHeightForWidth())
        self.exitB.setSizePolicy(sizePolicy)
        self.exitB.setMinimumSize(QtCore.QSize(0, 50))
        self.exitB.setObjectName("exitB")
        self.gridLayout_5.addWidget(self.exitB, 2, 1, 1, 1)
        self.openB = QtWidgets.QPushButton(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.openB.sizePolicy().hasHeightForWidth())
        self.openB.setSizePolicy(sizePolicy)
        self.openB.setMinimumSize(QtCore.QSize(0, 50))
        self.openB.setObjectName("openB")
        self.gridLayout_5.addWidget(self.openB, 0, 1, 1, 1)
        self.findPlayerB = QtWidgets.QPushButton(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.findPlayerB.sizePolicy().hasHeightForWidth())
        self.findPlayerB.setSizePolicy(sizePolicy)
        self.findPlayerB.setMinimumSize(QtCore.QSize(0, 50))
        self.findPlayerB.setObjectName("findPlayerB")
        self.gridLayout_5.addWidget(self.findPlayerB, 1, 1, 1, 1)
        self.gridLayout_2.addWidget(self.groupBox, 2, 1, 1, 1)
        self.scrollArea = QtWidgets.QScrollArea(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.scrollArea.sizePolicy().hasHeightForWidth())
        self.scrollArea.setSizePolicy(sizePolicy)
        self.scrollArea.setMinimumSize(QtCore.QSize(700, 0))
        self.scrollArea.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.scrollArea.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.scrollArea.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustIgnored)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 698, 474))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.gridLayout_8 = QtWidgets.QGridLayout(self.scrollAreaWidgetContents)
        self.gridLayout_8.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.tourGrid = QtWidgets.QGridLayout()
        self.tourGrid.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.tourGrid.setContentsMargins(3, 3, 3, 3)
        self.tourGrid.setHorizontalSpacing(6)
        self.tourGrid.setObjectName("tourGrid")
        self.gridLayout_8.addLayout(self.tourGrid, 0, 0, 1, 1)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.gridLayout_2.addWidget(self.scrollArea, 0, 0, 2, 1)
        self.scrollArea_2 = QtWidgets.QScrollArea(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.scrollArea_2.sizePolicy().hasHeightForWidth())
        self.scrollArea_2.setSizePolicy(sizePolicy)
        self.scrollArea_2.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.scrollArea_2.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.scrollArea_2.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustIgnored)
        self.scrollArea_2.setWidgetResizable(True)
        self.scrollArea_2.setObjectName("scrollArea_2")
        self.scrollAreaWidgetContents_3 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_3.setGeometry(QtCore.QRect(0, 0, 698, 248))
        self.scrollAreaWidgetContents_3.setObjectName("scrollAreaWidgetContents_3")
        self.gridLayout_10 = QtWidgets.QGridLayout(self.scrollAreaWidgetContents_3)
        self.gridLayout_10.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_10.setObjectName("gridLayout_10")
        self.courtGrid = QtWidgets.QGridLayout()
        self.courtGrid.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.courtGrid.setContentsMargins(3, 3, 3, 3)
        self.courtGrid.setHorizontalSpacing(6)
        self.courtGrid.setObjectName("courtGrid")
        self.gridLayout_10.addLayout(self.courtGrid, 0, 0, 1, 1)
        self.scrollArea_2.setWidget(self.scrollAreaWidgetContents_3)
        self.gridLayout_2.addWidget(self.scrollArea_2, 2, 0, 2, 1)
        self.groupBox_6 = QtWidgets.QGroupBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_6.sizePolicy().hasHeightForWidth())
        self.groupBox_6.setSizePolicy(sizePolicy)
        self.groupBox_6.setMinimumSize(QtCore.QSize(200, 0))
        self.groupBox_6.setMaximumSize(QtCore.QSize(600, 16777215))
        self.groupBox_6.setObjectName("groupBox_6")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.groupBox_6)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(self.groupBox_6)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.butSizeSlider = QtWidgets.QSlider(self.groupBox_6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.butSizeSlider.sizePolicy().hasHeightForWidth())
        self.butSizeSlider.setSizePolicy(sizePolicy)
        self.butSizeSlider.setMinimum(5)
        self.butSizeSlider.setMaximum(12)
        self.butSizeSlider.setProperty("value", 7)
        self.butSizeSlider.setSliderPosition(7)
        self.butSizeSlider.setOrientation(QtCore.Qt.Horizontal)
        self.butSizeSlider.setObjectName("butSizeSlider")
        self.verticalLayout.addWidget(self.butSizeSlider)
        self.label_4 = QtWidgets.QLabel(self.groupBox_6)
        self.label_4.setObjectName("label_4")
        self.verticalLayout.addWidget(self.label_4)
        self.fontSizeSlider = QtWidgets.QSlider(self.groupBox_6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.fontSizeSlider.sizePolicy().hasHeightForWidth())
        self.fontSizeSlider.setSizePolicy(sizePolicy)
        self.fontSizeSlider.setMinimum(5)
        self.fontSizeSlider.setMaximum(15)
        self.fontSizeSlider.setProperty("value", 10)
        self.fontSizeSlider.setSliderPosition(10)
        self.fontSizeSlider.setOrientation(QtCore.Qt.Horizontal)
        self.fontSizeSlider.setObjectName("fontSizeSlider")
        self.verticalLayout.addWidget(self.fontSizeSlider)
        self.label_2 = QtWidgets.QLabel(self.groupBox_6)
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.depthSlider = QtWidgets.QSlider(self.groupBox_6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.depthSlider.sizePolicy().hasHeightForWidth())
        self.depthSlider.setSizePolicy(sizePolicy)
        self.depthSlider.setMinimum(3)
        self.depthSlider.setMaximum(7)
        self.depthSlider.setSliderPosition(4)
        self.depthSlider.setOrientation(QtCore.Qt.Horizontal)
        self.depthSlider.setObjectName("depthSlider")
        self.verticalLayout.addWidget(self.depthSlider)
        self.label_3 = QtWidgets.QLabel(self.groupBox_6)
        self.label_3.setObjectName("label_3")
        self.verticalLayout.addWidget(self.label_3)
        self.courtNumSlider = QtWidgets.QSlider(self.groupBox_6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.courtNumSlider.sizePolicy().hasHeightForWidth())
        self.courtNumSlider.setSizePolicy(sizePolicy)
        self.courtNumSlider.setMinimum(0)
        self.courtNumSlider.setMaximum(20)
        self.courtNumSlider.setPageStep(1)
        self.courtNumSlider.setProperty("value", 14)
        self.courtNumSlider.setSliderPosition(14)
        self.courtNumSlider.setOrientation(QtCore.Qt.Horizontal)
        self.courtNumSlider.setObjectName("courtNumSlider")
        self.verticalLayout.addWidget(self.courtNumSlider)
        self.gridLayout_2.addWidget(self.groupBox_6, 1, 1, 1, 1)
        self.groupBox_5 = QtWidgets.QGroupBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_5.sizePolicy().hasHeightForWidth())
        self.groupBox_5.setSizePolicy(sizePolicy)
        self.groupBox_5.setMinimumSize(QtCore.QSize(200, 200))
        self.groupBox_5.setMaximumSize(QtCore.QSize(600, 16777215))
        self.groupBox_5.setObjectName("groupBox_5")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.groupBox_5)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.waitingMatches = QtWidgets.QTableWidget(self.groupBox_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.waitingMatches.sizePolicy().hasHeightForWidth())
        self.waitingMatches.setSizePolicy(sizePolicy)
        self.waitingMatches.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.waitingMatches.setDragDropOverwriteMode(False)
        self.waitingMatches.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.waitingMatches.setObjectName("waitingMatches")
        self.waitingMatches.setColumnCount(5)
        self.waitingMatches.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.waitingMatches.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.waitingMatches.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.waitingMatches.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.waitingMatches.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.waitingMatches.setHorizontalHeaderItem(4, item)
        self.gridLayout_7.addWidget(self.waitingMatches, 0, 0, 1, 1)
        self.gridLayout_2.addWidget(self.groupBox_5, 0, 1, 1, 1)
        self.testB = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.testB.sizePolicy().hasHeightForWidth())
        self.testB.setSizePolicy(sizePolicy)
        self.testB.setMinimumSize(QtCore.QSize(200, 50))
        self.testB.setMaximumSize(QtCore.QSize(600, 16777215))
        self.testB.setObjectName("testB")
        self.gridLayout_2.addWidget(self.testB, 3, 1, 1, 1)
        TournamentController.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(TournamentController)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1145, 21))
        self.menubar.setObjectName("menubar")
        TournamentController.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(TournamentController)
        self.statusbar.setObjectName("statusbar")
        TournamentController.setStatusBar(self.statusbar)

        self.retranslateUi(TournamentController)
        QtCore.QMetaObject.connectSlotsByName(TournamentController)

    def retranslateUi(self, TournamentController):
        _translate = QtCore.QCoreApplication.translate
        TournamentController.setWindowTitle(_translate("TournamentController", "MainWindow"))
        self.groupBox.setTitle(_translate("TournamentController", "System Editor"))
        self.findMatchB.setText(_translate("TournamentController", "Find Match"))
        self.saveB.setText(_translate("TournamentController", "Save"))
        self.editB.setText(_translate("TournamentController", "Edit"))
        self.exitB.setText(_translate("TournamentController", "Exit"))
        self.openB.setText(_translate("TournamentController", "Open"))
        self.findPlayerB.setText(_translate("TournamentController", "Find Player"))
        self.groupBox_6.setTitle(_translate("TournamentController", "System Controllers"))
        self.label.setText(_translate("TournamentController", "Button Size"))
        self.label_4.setText(_translate("TournamentController", "Font Size"))
        self.label_2.setText(_translate("TournamentController", "Showing Depth"))
        self.label_3.setText(_translate("TournamentController", "Court Number"))
        self.groupBox_5.setTitle(_translate("TournamentController", "Comming Up Match"))
        item = self.waitingMatches.horizontalHeaderItem(0)
        item.setText(_translate("TournamentController", "Match Level"))
        item = self.waitingMatches.horizontalHeaderItem(1)
        item.setText(_translate("TournamentController", "Player1"))
        item = self.waitingMatches.horizontalHeaderItem(2)
        item.setText(_translate("TournamentController", "Player2"))
        item = self.waitingMatches.horizontalHeaderItem(3)
        item.setText(_translate("TournamentController", "UpperMatches"))
        item = self.waitingMatches.horizontalHeaderItem(4)
        item.setText(_translate("TournamentController", "MatchNum"))
        self.testB.setText(_translate("TournamentController", "Test"))
class Ui_InfoDialog(object):
    def setupUi(self, CourtInfo):
        CourtInfo.setObjectName("CourtInfo")

        CourtInfo.resize(492, 309)
        self.buttonBox = QtWidgets.QDialogButtonBox(CourtInfo)
        self.buttonBox.setGeometry(QtCore.QRect(120, 240, 341, 32))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")

        self.courtInfo = QtWidgets.QLabel(CourtInfo)
        self.courtInfo.setGeometry(QtCore.QRect(80, 30, 141, 51))
        self.courtInfo.setObjectName("courtInfo")

        self.player1Name = QtWidgets.QLabel(CourtInfo)
        self.player1Name.setGeometry(QtCore.QRect(80, 90, 141, 51))
        self.player1Name.setObjectName("player1Name")

        self.player2Name = QtWidgets.QLabel(CourtInfo)
        self.player2Name.setGeometry(QtCore.QRect(280, 90, 141, 51))
        self.player2Name.setObjectName("player2Name")

        self.player1Score = QtWidgets.QLabel(CourtInfo)
        self.player1Score.setGeometry(QtCore.QRect(80, 160, 141, 61))
        self.player1Score.setObjectName("player1Score")

        self.player1Up = QtWidgets.QPushButton(CourtInfo)
        self.player1Up.setGeometry(QtCore.QRect(220, 170, 21, 21))
        self.player1Up.setObjectName("player1Up")

        self.player1Down = QtWidgets.QPushButton(CourtInfo)
        self.player1Down.setGeometry(QtCore.QRect(220, 190, 21, 21))
        self.player1Down.setObjectName("player1Down")

        self.player2Score = QtWidgets.QLabel(CourtInfo)
        self.player2Score.setGeometry(QtCore.QRect(280, 160, 141, 61))
        self.player2Score.setObjectName("player2Score")

        self.player2Up = QtWidgets.QPushButton(CourtInfo)
        self.player2Up.setGeometry(QtCore.QRect(420, 170, 21, 21))
        self.player2Up.setObjectName("player2Up")

        self.player2Down = QtWidgets.QPushButton(CourtInfo)
        self.player2Down.setGeometry(QtCore.QRect(420, 190, 21, 21))
        self.player2Down.setObjectName("player2Down")

        self.endMatchB = QtWidgets.QPushButton(CourtInfo)
        self.endMatchB.setGeometry(QtCore.QRect(320, 40, 131, 31))
        self.endMatchB.setObjectName("endMatchB")


        self.retranslateUi(CourtInfo)
        self.buttonBox.accepted.connect(CourtInfo.accept)
        self.buttonBox.rejected.connect(CourtInfo.reject)
        QtCore.QMetaObject.connectSlotsByName(CourtInfo)

    def retranslateUi(self, CourtInfo):
        _translate = QtCore.QCoreApplication.translate
        CourtInfo.setWindowTitle(_translate("CourtInfo", "Dialog"))
        self.courtInfo.setText(_translate("CourtInfo", "Court X Information\nMatch X(**강)"))
        self.player1Name.setText(_translate("CourtInfo", "Player 1 : "))
        self.player2Name.setText(_translate("CourtInfo", "Player 2 : "))
        self.player1Score.setText(_translate("CourtInfo", "Player 1 Score : "))
        self.player1Up.setText(_translate("CourtInfo", "+"))
        self.player1Down.setText(_translate("CourtInfo", "-"))
        self.player2Score.setText(_translate("CourtInfo", "Player 2 Score : "))
        self.player2Up.setText(_translate("CourtInfo", "+"))
        self.player2Down.setText(_translate("CourtInfo", "-"))
        self.endMatchB.setText(_translate("CourtInfo", "End Match"))


class Ui_EndCheckDialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(400, 300)
        self.buttonBox = QtWidgets.QDialogButtonBox(Dialog)
        self.buttonBox.setGeometry(QtCore.QRect(30, 240, 341, 32))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.player1Name_2 = QtWidgets.QLabel(Dialog)
        self.player1Name_2.setGeometry(QtCore.QRect(30, 140, 341, 61))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.player1Name_2.setFont(font)
        self.player1Name_2.setAlignment(QtCore.Qt.AlignCenter)
        self.player1Name_2.setObjectName("player1Name_2")
        self.player1Name = QtWidgets.QLabel(Dialog)
        self.player1Name.setGeometry(QtCore.QRect(60, 40, 291, 101))
        self.player1Name.setAlignment(QtCore.Qt.AlignCenter)
        self.player1Name.setObjectName("player1Name")

        self.retranslateUi(Dialog)
        self.buttonBox.accepted.connect(Dialog.accept)
        self.buttonBox.rejected.connect(Dialog.reject)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.player1Name_2.setText(_translate("Dialog", "확정하시겠습니까??\n\
        (경기 결과를 확정하면 더이상 수정할 수 없습니다)"))
        self.player1Name.setText(_translate("Dialog", "현재 경기의 정보는 \
        다음과 같습니다\nMatch #{matchnum}\nPlayer: {ply1}:{ply2}\n\
        Score : {scr1}:{scr2}"))


class Ui_CourtSetDialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(368, 271)
        self.verticalLayout = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.waitingMatches = QtWidgets.QComboBox(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.waitingMatches.sizePolicy().hasHeightForWidth())
        self.waitingMatches.setSizePolicy(sizePolicy)
        self.waitingMatches.setMinimumSize(QtCore.QSize(350, 20))
        self.waitingMatches.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.waitingMatches.setSizeAdjustPolicy(QtWidgets.QComboBox.AdjustToContents)
        self.waitingMatches.setObjectName("waitingMatches")
        self.verticalLayout.addWidget(self.waitingMatches)
        self.buttonBox = QtWidgets.QDialogButtonBox(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.buttonBox.sizePolicy().hasHeightForWidth())
        self.buttonBox.setSizePolicy(sizePolicy)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout.addWidget(self.buttonBox)

        self.retranslateUi(Dialog)
        self.buttonBox.accepted.connect(Dialog.accept)
        self.buttonBox.rejected.connect(Dialog.reject)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label.setText(_translate("Dialog", "Court {0}에 배정된 경기가 없습니다.\n"
"경기를 배정하십시오"))
